touchscreen: gt1x: Don't use clang's builtin defs for fwrite
We have it defined in the driver itself. Using clang's defs leads to errors like:

drivers/built-in.o: In function `_save_testing_data':
kernel/nokia/sdm660/drivers/input/touchscreen/gt1x/test_function.c:1065: undefined reference to `fwrite_unlocked'
kernel/nokia/sdm660/drivers/input/touchscreen/gt1x/test_function.c:1087: undefined reference to `fwrite_unlocked'
kernel/nokia/sdm660/drivers/input/touchscreen/gt1x/test_function.c:939: undefined reference to `fwrite_unlocked'
kernel/nokia/sdm660/drivers/input/touchscreen/gt1x/test_function.c:953: undefined reference to `fwrite_unlocked'
kernel/nokia/sdm660/drivers/input/touchscreen/gt1x/test_function.c:1104: undefined reference to `fwrite_unlocked'
drivers/built-in.o:kernel/nokia/sdm660/drivers/input/touchscreen/gt1x/test_function.c:1112: more undefined references to `fwrite_unlocked' follow

- Required after: https://github.com/llvm-mirror/clang/commit/0504bf2ebb0949b0d304829406dcbe7793d0d42f

Change-Id: I61498d2f14afb194df723c3fea31aee4a572b6ed
Signed-off-by: theimpulson <aayushgupta219@gmail.com>